[package]
name = "tokio_practical_combat_demo"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.20" }
